framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - App\Infrastructure\Messenger\Middleware\ValidationMiddleware
                    - doctrine_transaction
            query.bus:
                middleware:
                    - App\Infrastructure\Messenger\Middleware\ValidationMiddleware
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
