nelmio_api_doc:
    documentation:
        info:
            title: Album API
            description: API for managing albums
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api/v1/