app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

controllers:
    resource:
        path: ../src/UserInterface/Http/Rest/Controller/
        namespace: App\UserInterface\Http\Rest\Controller
    type: attribute